[package]
name = "tokenitis"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.10.0"
spl-token = {version = "3.3.0", features = ["no-entrypoint"]}
borsh = "0.9.3"

[lib]
crate-type = ["cdylib", "lib"]
